server:
  port: 8001

winning-numbers:
  url: localhost:8090

spring:
  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@mongo:27017/lotto-web?authSource=admin


#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core:
#              MongoTemplate: DEBUG
